
      SUBROUTINE SETUP_COSY(KORDER, KVAR, KMAXMEM)
*     ********************************************
*     Wrapper to initialize COSY from scalar integers
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
*
*-----MEMORY MANAGEMENT -----------------------------------------------------
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC
      COMMON /FOXTYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
*----------------------------------------------------------------------------
      INTEGER KORDER, KVAR, KMAXMEM
      INTEGER INO, INV, IIU, INM
      INTEGER IC(1)
*
*     Allocate and set Order object
      CALL FOXALL(IC, 1, 1)
      INO = IC(1)
      CC(NBEG(INO)) = DBLE(KORDER)
*
*     Allocate and set Dimension object
      CALL FOXALL(IC, 1, 1)
      INV = IC(1)
      CC(NBEG(INV)) = DBLE(KVAR)
*
*     Allocate and set Unit object
      CALL FOXALL(IC, 1, 1)
      IIU = IC(1)
      CC(NBEG(IIU)) = 6.0D0
*
*     Allocate Output Max Memory object
      CALL FOXALL(IC, 1, 1)
      INM = IC(1)
*
*     Call original DAINI
      CALL DAINI(INO, INV, IIU, INM)
*
*     Return actual Max Monomials
      KMAXMEM = NINT(CC(NBEG(INM)))
*
      RETURN
      END

      SUBROUTINE GET_VAR_IDX(IDX)
*     ***************************
*     Allocates a new generic variable and returns its index
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, IC(1)
      
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
      CALL FOXALL(IC, 1, NMMAX)
      IDX = IC(1)
      RETURN
      END
      
      SUBROUTINE CREATE_DA_VAR(KIVAR, RES_IDX)
*     ***************************************
*     Creates a DA variable for the independent variable IVAR (1..DIM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
*     Include Common Blocks
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC

      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
     
      INTEGER KIVAR, RES_IDX
      INTEGER IIV, IC(1)
      
*     Allocate Result Variable with NMMAX
      CALL FOXALL(IC, 1, NMMAX)
      RES_IDX = IC(1)

*     We need to wrap IVAR in a COSY object
      CALL FOXALL(IC, 1, 1)
      IIV = IC(1)
      CC(NBEG(IIV)) = DBLE(KIVAR)
      
*     Now call DA
      CALL DA(IIV, RES_IDX)
      
*     Cleanup temporary IIV
      IC(1) = IIV
      CALL FOXDAL(IC, 1)
      
      RETURN
      END

      SUBROUTINE GET_DA_COEFF(DA_IDX, EXPS, COEFF)
*     ********************************************
*     Extracts coefficient for a given exponent array
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DA_IDX
      INTEGER EXPS(*) 
      DOUBLE PRECISION COEFF
      
*     Parameters matching dafox.f
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC
      COMMON /FOXTYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
      INTEGER I1, I2, NM, I, K
      INTEGER JJ(LNV)
      
*     Zero JJ first
      DO 5 K=1,LNV
         JJ(K) = 0
 5    CONTINUE

*      OPEN(UNIT=99, FILE='/home/mls/work/COSY10p2/cosy_debug.log', 
*     *     STATUS='UNKNOWN')
*      WRITE(99,*) 'DEBUG: NVMAX=', NVMAX, ' DA_IDX=', DA_IDX
*      CLOSE(99)

*     Convert input exponents to local JJ array (size LNV)
*     Only copy up to current dimension NVMAX
      DO 10 I=1,NVMAX
         JJ(I) = EXPS(I)
 10   CONTINUE

*      PRINT *, 'DEBUG: GET_DA_COEFF DA_IDX=', DA_IDX, ' NVMAX=', NVMAX
*      PRINT *, 'DEBUG: EXPS=', (JJ(K), K=1,NVMAX)
      
*     Encode exponents to I1, I2
      CALL DADEC(JJ, I1, I2)
      
*     Calculate Monomial Index NM using IA1/IA2
      NM = IA1(I1) + IA2(I2)
      
*     Now search for NM in the DA variable's NC array
      COEFF = 0.0D0
      
      DO 20 I = NBEG(DA_IDX), NEND(DA_IDX)
         IF (NC(I).EQ.NM) THEN
             COEFF = CC(I)
             RETURN
         ENDIF
 20   CONTINUE
      
      RETURN
      END

      SUBROUTINE SET_DA_COEFF(DA_IDX, EXPS, COEFF)
*     ********************************************
*     Sets coefficient. Placeholder.
      RETURN
      END

      SUBROUTINE EVAL_DA(DA_IDX, POINT, RES)
*     **************************************
*     Evaluates DA variable at a point
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DA_IDX
      DOUBLE PRECISION POINT(*)
      DOUBLE PRECISION RES
      
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC
      COMMON /FOXTYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
      INTEGER JJ(LNV)
      INTEGER I, K, NM, I1, I2, EXP
      DOUBLE PRECISION TERM, PVAL
      
      RES = 0.0D0
      
      DO 100 I = NBEG(DA_IDX), NEND(DA_IDX)
         NM = NC(I)
*        Decode NM to Exponents JJ
         CALL DAENC(IE1(NM), IE2(NM), JJ)
         
         TERM = CC(I)
         
*        Multiply by variables
         DO 50 K=1,NVMAX
             EXP = JJ(K)
             IF (EXP .GT. 0) THEN
                 TERM = TERM * (POINT(K) ** EXP)
             ENDIF
 50      CONTINUE
         
         RES = RES + TERM
 100  CONTINUE
      
      RETURN
      END

      SUBROUTINE CREATE_DA_CONST(VAL, RES_IDX)
*     ****************************************
*     Creates a DA variable initialized to a constant value
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION VAL
      INTEGER RES_IDX, IC(1)

      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
*     Allocate Result Variable with NMMAX
      CALL FOXALL(IC, 1, NMMAX)
      RES_IDX = IC(1)
      
      CALL DACON(RES_IDX, VAL)
      
*      PRINT *, 'DEBUG: CREATE_DA_CONST VAL=', VAL, ' RES=', RES_IDX
      RETURN
      END
      
      SUBROUTINE COMPUTE_DA_DIV(IDX_A, IDX_B, IDX_RES)
*     ************************************************
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES
      INTEGER IC(1)
      
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_EXP(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAEXP(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_LOG(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DALOG(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SIN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASINE(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COS(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOSE(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SQRT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASQRT(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SQR(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASQR(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ERF(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAERF(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADCOT(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COTH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOTH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ISRT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAISRT(IDX_IN, IDX_RES)
      RETURN
      END


      SUBROUTINE COMPUTE_DA_NORM(IDX_IN, RES_VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IC(1), INORM
      DOUBLE PRECISION RES_VAL
      
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC

      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      
      CALL FOXALL(IC, 1, 1)
      INORM = IC(1)
      CALL DANOR(IDX_IN, INORM)
      RES_VAL = CC(NBEG(INORM))
      IC(1) = INORM
      CALL FOXDAL(IC, 1)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_TAN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADTAN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ASIN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAASIN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ACOS(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAACOS(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ATAN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAATAN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SINH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASINH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COSH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOSH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_TANH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DATANH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE GET_DA_NUM_TERMS(DA_IDX, N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DA_IDX, N
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC
      
      IF (DA_IDX .LT. 1 .OR. DA_IDX .GT. LVAR) THEN
         N = 0
         RETURN
      ENDIF

      IF (NEND(DA_IDX) .LT. NBEG(DA_IDX)) THEN
         N = 0
      ELSE
         N = NEND(DA_IDX) - NBEG(DA_IDX) + 1
      ENDIF
      RETURN
      END

      SUBROUTINE GET_DA_TERM_DECODED(DA_IDX, ITERM, EXPS, COEFF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DA_IDX, ITERM, EXPS(*)
      DOUBLE PRECISION COEFF
      
      PARAMETER(LMEM=2000000,LVAR=100000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON /DAFOXINT/ NTYP,NBEG,NEND,NMAX, NC, NDIM,IDIM, IVAR,IMEM
      COMMON /DAFOXDBL/ CC
      
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT

      INTEGER JJ(LNV)

      IF (DA_IDX .LT. 1 .OR. DA_IDX .GT. LVAR) RETURN

      I = NBEG(DA_IDX) + ITERM - 1
      COEFF = CC(I)
      NM = NC(I)
      
      IF (NM .EQ. 0) THEN
         DO 10 K=1, NVMAX
  10     EXPS(K) = 0
      ELSE
         CALL DAENC(IE1(NM), IE2(NM), JJ)
         DO 20 K=1, NVMAX
  20     EXPS(K) = JJ(K)
      ENDIF
      RETURN
      END


