from langchain_core.tools import tool

from sandalwood.agent_tools import functions

initialize_sandalwood = tool(functions.initialize_sandalwood)
parse_expression_to_mtf = tool(functions.parse_expression_to_mtf)
create_taylor_map = tool(functions.create_taylor_map)
evaluate_taylor_map = tool(functions.evaluate_taylor_map)
evaluate_mtf = tool(functions.evaluate_mtf)
invert_taylor_map = tool(functions.invert_taylor_map)
compute_partial_derivative = tool(functions.compute_partial_derivative)
integrate_mtf = tool(functions.integrate_mtf)
compose_taylor_maps = tool(functions.compose_taylor_maps)
compose_mtfs = tool(functions.compose_mtfs)
perform_mtf_arithmetic = tool(functions.perform_mtf_arithmetic)
perform_complex_operation = tool(functions.perform_complex_operation)
mtf_info = tool(functions.mtf_info)
taylor_map_info = tool(functions.taylor_map_info)
substitute_variable_in_mtf = tool(functions.substitute_variable_in_mtf)
substitute_in_taylor_map = tool(functions.substitute_in_taylor_map)
get_mtf_coefficient = tool(functions.get_mtf_coefficient)
truncate_object = tool(functions.truncate_object)
analyze_taylor_map = tool(functions.analyze_taylor_map)
evaluate_mtf_batch = tool(functions.evaluate_mtf_batch)
evaluate_taylor_map_batch = tool(functions.evaluate_taylor_map_batch)
analyze_mtf_diagnostics = tool(functions.analyze_mtf_diagnostics)
compute_poisson_bracket = tool(functions.compute_poisson_bracket)
compute_map_sensitivity = tool(functions.compute_map_sensitivity)
extract_map_component = tool(functions.extract_map_component)
