      SUBROUTINE DEBUG_PRINT_TYPE(IDX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX
      
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      INTEGER NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      COMMON /TYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR

      PRINT *, "DEBUG: IDX=", IDX, " NTYP=", NTYP(IDX), " NCD=", NCD, " NDA=", NDA
      RETURN
      END
