      SUBROUTINE SETUP_COSY(KORDER, KVAR, KMAXMEM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER KORDER, KVAR, KMAXMEM
*
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      COMMON /TYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
*
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
*
      INTEGER IC(1), INO, INV, IIU, INM
*
      CALL FOXALL(IC, 1, 1)
      INO = IC(1)
      CC(NBEG(INO)) = DBLE(KORDER)
*
      CALL FOXALL(IC, 1, 1)
      INV = IC(1)
      CC(NBEG(INV)) = DBLE(KVAR)
*
      CALL FOXALL(IC, 1, 1)
      IIU = IC(1)
      CC(NBEG(IIU)) = 6.0D0
*
      CALL FOXALL(IC, 1, 1)
      INM = IC(1)
*
      CALL DAINI(INO, INV, IIU, INM)
*
      KMAXMEM = NINT(CC(NBEG(INM)))
*
      RETURN
      END

      SUBROUTINE COSY_FREE(IDX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, IC(1)
      IC(1) = IDX
      CALL FOXDAL(IC, 1)
      RETURN
      END

      SUBROUTINE GET_DA_COEFF(IDX, EXPS, VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, EXPS(*)
      DOUBLE PRECISION VAL
      INTEGER I, K, NM, JJ(40)
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL DAENE(EXPS, NM)
      VAL = 0.0D0
      IF (NEND(IDX) .LT. NBEG(IDX)) RETURN
      DO 100 I = NBEG(IDX), NEND(IDX)
         IF (NC(I) .EQ. NM) THEN
            VAL = CC(I)
            RETURN
         ENDIF
 100  CONTINUE
      RETURN
      END

      SUBROUTINE CREATE_DA_VAR(IDX, VAL, VARID)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, VARID, IC(1)
      DOUBLE PRECISION VAL
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX = IC(1)
      CALL DAVAR(IDX, VAL, VARID)
      RETURN
      END

      SUBROUTINE CREATE_DA_CONST(IDX, VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, IC(1)
      DOUBLE PRECISION VAL
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX = IC(1)
      CALL DACON(IDX, VAL)
      RETURN
      END

      SUBROUTINE EVAL_DA(IDX, POINTS, VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX
      DOUBLE PRECISION POINTS(*), VAL
      INTEGER I, K, NM, JJ(40)
      DOUBLE PRECISION TERM, COEFF
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      
      VAL = 0.0D0
      IF (NEND(IDX) .LT. NBEG(IDX)) RETURN
      
      DO 100 I = NBEG(IDX), NEND(IDX)
         COEFF = CC(I)
         IF (ABS(COEFF) .GT. 0.0D0) THEN
             NM = NC(I)
             IF (NM .EQ. 0) THEN
                 TERM = 1.0D0
             ELSE
                 CALL DAENC(IE1(NM), IE2(NM), JJ)
                 TERM = 1.0D0
                 DO 50 K = 1, NVMAX
                     IF (JJ(K) .GT. 0) THEN
                         TERM = TERM * (POINTS(K)**JJ(K))
                     ENDIF
 50              CONTINUE
             ENDIF
             VAL = VAL + COEFF * TERM
         ENDIF
 100  CONTINUE
      RETURN
      END

      SUBROUTINE COSY_SET_COEFFS(IDX, VALS, EXPS, N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, N, EXPS(*), I, J, NM, K
      DOUBLE PRECISION VALS(N)
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:1400000),IA2(0:1400000),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      INTEGER JJ(LNV)
      
      CALL DACON(IDX, 0.0D0)
      
      DO 100 I = 1, N
          DO 10 K = 1, NVMAX
              JJ(K) = EXPS((I-1)*NVMAX + K)
 10       CONTINUE
          CALL DAENE(JJ, NM)
          IF (NM .GT. 0) THEN
             J = NBEG(IDX) + I - 1
             IF (J .LE. NMAX(IDX)) THEN
                CC(J) = VALS(I)
                NC(J) = NM
                NEND(IDX) = MAX(NEND(IDX), J)
             ENDIF
          ENDIF
 100  CONTINUE
      RETURN
      END

      SUBROUTINE COSY_SET_CD_COEFFS(IDX, RE_VALS, IM_VALS, EXPS, N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, N, EXPS(*), I, J, NM, K
      DOUBLE PRECISION RE_VALS(N), IM_VALS(N)
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:1400000),IA2(0:1400000),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      INTEGER JJ(LNV)
      INTEGER IC(3), ITRE, ITIM
      
      ! Initialize to zero (Complex)
      CALL FOXALL(IC, 2, NMMAX)
      CALL DACON(IC(1), 0.0D0)
      CALL DACON(IC(2), 0.0D0)
      CALL SET_CD_PARTS(IDX, IC(1), IC(2))
      CALL FOXDAL(IC, 2)
      
      DO 200 I = 1, N
          DO 20 K = 1, NVMAX
              JJ(K) = EXPS((I-1)*NVMAX + K)
 20       CONTINUE
          CALL DAENE(JJ, NM)
          IF (NM .GT. 0) THEN
             J = NBEG(IDX) + (I - 1) * 2
             IF ((J+1) .LE. NMAX(IDX)) THEN
                CC(J)   = RE_VALS(I)
                CC(J+1) = IM_VALS(I)
                NC(J)   = NM
                NC(J+1) = NM
                NEND(IDX) = MAX(NEND(IDX), J+1)
             ENDIF
          ENDIF
 200  CONTINUE
      RETURN
      END

      SUBROUTINE GET_DA_COEFF_BY_INDEX(IDX, ITERM, EXPS, VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, ITERM, EXPS(*)
      DOUBLE PRECISION VAL
      INTEGER I, K, NM, JJ(40)
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      I = NBEG(IDX) + ITERM - 1
      IF (I .GT. NEND(IDX)) THEN
          VAL = 0.0D0
          RETURN
      ENDIF
      VAL = CC(I)
      NM = NC(I)
      IF (NM .GT. 0) THEN
         CALL DAENC(IE1(NM), IE2(NM), JJ)
         DO 10 K = 1, NVMAX
             EXPS(K) = JJ(K)
 10      CONTINUE
      ELSE
         DO 11 K = 1, NVMAX
             EXPS(K) = 0
 11      CONTINUE
      ENDIF
      RETURN
      END
      SUBROUTINE GET_CDA_COEFF_BY_INDEX(IDX, ITERM, EXPS, RE_VAL, 
     *  IM_VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, ITERM, EXPS(*)
      DOUBLE PRECISION RE_VAL, IM_VAL
      INTEGER I, K, NM, JJ(40)
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      I = NBEG(IDX) + (ITERM - 1) * 2
      IF (I .GT. NEND(IDX)) THEN
          RE_VAL = 0.0D0
          IM_VAL = 0.0D0
          RETURN
      ENDIF
      RE_VAL = CC(I)
      IM_VAL = CC(I+1)
      NM = NC(I)
      CALL DAENC(IE1(NM), IE2(NM), JJ)
      DO 10 K = 1, NVMAX
          EXPS(K) = JJ(K)
 10   CONTINUE
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ADD(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAADA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SUB(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_MUL(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAMDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_DIV(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_DER(IDX_IN, IVAR, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IVAR, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADER(IVAR, IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_INT(IDX_IN, IVAR, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IVAR, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAINT(IVAR, IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_POI(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAPOI2(IDX_A, IDX_B, IDX_RES, NVMAX)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_EXP(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAEXP(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_LOG(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DALOG(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SIN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASINE(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COS(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOSE(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_TAN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADTAN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SQRT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASQRT(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SQR(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASQR(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_SINH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASINH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COSH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOSH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_TANH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DATANH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ASIN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAASIN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ACOS(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAACOS(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ATAN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAATAN(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COTH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOTH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ASINH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DASINH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ACOSH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DACOSH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ATANH(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DATANH(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_MINV(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAMUI(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ISRT3(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAISR3(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_DAEST(IDX_IN, VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN
      DOUBLE PRECISION VAL
      VAL = 0.0D0
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ISRT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAISRT(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_ERF(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DAERF(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_COT(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL DADCOT(IDX_IN, IDX_RES)
      RETURN
      END

      SUBROUTINE CREATE_CDA_VAR(IDX, VARID, RE_VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, VARID, IC(1)
      DOUBLE PRECISION RE_VAL
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, 2*NMMAX)
      IDX = IC(1)
      CALL RECD(VARID, IDX)
      RETURN
      END

      SUBROUTINE CREATE_CDA_CONST(IDX, RE_VAL, IM_VAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, IC(3)
      DOUBLE PRECISION RE_VAL, IM_VAL
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 3, 2*NMMAX)
      IDX = IC(1)
      ITRE = IC(2)
      ITIM = IC(3)
      CALL DACON(ITRE, RE_VAL)
      CALL DACON(ITIM, IM_VAL)
      CALL SET_CD_PARTS(IDX, ITRE, ITIM)
      CALL FOXDAL(IC(2), 2)
      RETURN
      END

      SUBROUTINE COMPUTE_CD_ADD(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL CDADA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_CD_SUB(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL CDSDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_CD_MUL(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL CDMDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE COMPUTE_CD_DIV(IDX_A, IDX_B, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_A, IDX_B, IDX_RES, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_RES = IC(1)
      CALL CDDDA(IDX_A, IDX_B, IDX_RES)
      RETURN
      END

      SUBROUTINE GET_MEM_STATE(IVAR_OUT, IMEM_OUT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IVAR_OUT, IMEM_OUT
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      IVAR_OUT = IVAR
      IMEM_OUT = IMEM
      RETURN
      END

      SUBROUTINE SET_MEM_STATE(IVAR_IN, IMEM_IN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IVAR_IN, IMEM_IN
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      IVAR = IVAR_IN
      IMEM = IMEM_IN
      RETURN
      END

      SUBROUTINE GET_ALL_COEFFS_FLAT(IDX, COEFFS_OUT, EXPS_OUT, 
     *                               MAX_LEN, ACTUAL_LEN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX, MAX_LEN, ACTUAL_LEN
      DOUBLE PRECISION COEFFS_OUT(*)
      INTEGER EXPS_OUT(*)
      
      INTEGER I, K, NM, JJ(40), POS
      PARAMETER(LMEM=140000000,LVAR=10000000,LDIM=1000)
      INTEGER NTYP(LVAR),NBEG(LVAR),NEND(LVAR),NMAX(LVAR),
     *        NC(LMEM),NDIM(LDIM)
      DOUBLE PRECISION CC(LMEM)
      COMMON NTYP, NBEG, NEND, NMAX, CC, NC, NDIM, IDIM, IVAR, IMEM
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      
      ACTUAL_LEN = 0
      IF (NEND(IDX) .LT. NBEG(IDX)) RETURN

      POS = 1
      DO 100 I = NBEG(IDX), NEND(IDX)
         IF (POS .GT. MAX_LEN) GOTO 200
         
         IF (ABS(CC(I)) .GT. 0.0D0) THEN
             COEFFS_OUT(POS) = CC(I)
             NM = NC(I)
             IF (NM .EQ. 0) THEN
                 DO 10 K = 1, NVMAX
                    EXPS_OUT((POS-1)*NVMAX + K) = 0
  10             CONTINUE
             ELSE
                 CALL DAENC(IE1(NM), IE2(NM), JJ)
                 DO 20 K = 1, NVMAX
                    EXPS_OUT((POS-1)*NVMAX + K) = JJ(K)
  20             CONTINUE
             ENDIF
             POS = POS + 1
         ENDIF
 100  CONTINUE
 
 200  ACTUAL_LEN = POS - 1
      RETURN
      END

      SUBROUTINE COMPUTE_CD_EXP(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES
      PRINT *, 'CDEXP NOT IMPLEMENTED'
      RETURN
      END

      SUBROUTINE COMPUTE_CD_SIN(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES
      PRINT *, 'CDSIN NOT IMPLEMENTED'
      RETURN
      END

      SUBROUTINE COMPUTE_CD_COS(IDX_IN, IDX_RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_IN, IDX_RES
      PRINT *, 'CDCOS NOT IMPLEMENTED'
      RETURN
      END

      SUBROUTINE GET_CDA_RE(IDX_CD, IDX_DA)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_CD, IDX_DA
      CALL CDRE(IDX_CD, IDX_DA)
      RETURN
      END

      SUBROUTINE GET_CDA_IM(IDX_CD, IDX_DA)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_CD, IDX_DA
      CALL CDIM(IDX_CD, IDX_DA)
      RETURN
      END

      SUBROUTINE SET_CD_PARTS(IDX_CD, IDX_RE, IDX_IM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_CD, IDX_RE, IDX_IM, IC(3)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 3, 2*NMMAX)
      ICD_IM = IC(1)
      I_UNIT = IC(2)
      ITMP   = IC(3)
      CALL CDCMPL(IDX_RE, IDX_CD)
      CALL CDCMPL(IDX_IM, ICD_IM)
      CALL IMUNIT(I_UNIT)
      CALL CDMCD(I_UNIT, ICD_IM, ITMP)
      CALL CDACD(IDX_CD, ITMP, IDX_CD)
      CALL FOXDAL(IC, 3)
      RETURN
      END

      SUBROUTINE COMPUTE_DA_TO_CD(IDX_DA, IDX_CD)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX_DA, IDX_CD, IC(1)
      PARAMETER(LEA=100000)
      COMMON /DACOM/ CDA(2*LEA),EPS,EPSMAC,IE1(LEA),IE2(LEA),
     *       IEO(LEA),IA1(0:1400000),IA2(0:1400000),NCFLT(LEA),
     *       IEW(40),IED(40),LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,
     *       LFLT,NFLT
      CALL FOXALL(IC, 1, NMMAX)
      IDX_CD = IC(1)
      CALL CDCMPL(IDX_DA, IDX_CD)
      RETURN
      END

      SUBROUTINE EVAL_DA_PT(IDX, POINT, RES)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IDX
      DOUBLE PRECISION POINT(*), RES
      CALL EVAL_DA(IDX, POINT, RES)
      RETURN
      END

      SUBROUTINE FOXSTL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PRINT *, '*** FOXSTL CALLED (Error in COSY Backend) ***'
      STOP
      END

      SUBROUTINE FOXSTP(I)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER I
      PRINT *, '*** FOXSTP CALLED with ', I
      STOP
      END

      SUBROUTINE DAENE(JJ, NM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER JJ(*), NM, IC1, IC2
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      CALL DADEC(JJ, IC1, IC2)
      NM = IA1(IC1) + IA2(IC2)
      RETURN
      END
