      SUBROUTINE DAGETNCA(IC1, IC2, NCA)
*     **********************************
*     HELPER TO GET NCA FROM IC1, IC2 SAFE ACCESS TO COMMON
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
*
*-----DIFFERENTIAL ALGEBRA --------------------------------------------------
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      COMMON /TMCOM/ TMT,TMS,EPSM,TOLTMR,ITM,LENTM,ITMPR
*----------------------------------------------------------------------------
      INTEGER IC1, IC2, NCA
      
      NCA = IA1(IC1) + IA2(IC2)
      
      RETURN
      END

      SUBROUTINE DAGETNVE(NVE_OUT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      COMMON /TMCOM/ TMT,TMS,EPSM,TOLTMR,ITM,LENTM,ITMPR
      INTEGER NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      COMMON /TYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      INTEGER NVE_OUT
      NVE_OUT = NVE
      RETURN
      END

      SUBROUTINE DAGETNVMAX(NV_OUT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(LEA=100000,LIA=1400000,LNO=99,LNV=40)
      INTEGER IE1(LEA),IE2(LEA),IEO(LEA),IA1(0:LIA),IA2(0:LIA),
     *        NCFLT(LEA),IEW(LNV),IED(LNV),LEW,LEWI,IESP,
     *        NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT,ITM,LENTM,ITMPR
      DOUBLE PRECISION CDA(2*LEA),EPS,EPSMAC,TMT,TMS,EPSM,TOLTMR
      COMMON /DACOM/ CDA,EPS,EPSMAC,IE1,IE2,IEO,IA1,IA2,NCFLT,
     *       IEW,IED,LEW,LEWI,IESP,NOMAX,NVMAX,NMMAX,NOCUT,LFLT,NFLT
      INTEGER NV_OUT
      NV_OUT = NVMAX
      RETURN
      END

      SUBROUTINE DAINIT_TYPES
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      COMMON /TYID/ NRE,NST,NLO,NCM,NVE,NDA,NCD,NGR
      NRE = 1
      NST = 2
      NLO = 3
      NCM = 4
      NVE = 5
      NDA = 6
      NCD = 7
      NGR = 8
      
      PRINT *, 'DBG: Types Init. NDA=', NDA, ' NRE=', NRE, ' NST=', NST
      PRINT *, 'DBG: NCM=', NCM, ' NVE=', NVE, ' NCD=', NCD, ' NGR=', NGR
      
      RETURN
      END
